[package]
edition = "2021"
name    = "runtime-overrides"
version = "0.1.0"

[dependencies]
# crates.io
anyhow     = { version = "1.0" }
clap       = { version = "3.0", features = ["derive"] }
serde_json = { version = "1.0" }
# github
subwasmlib  = { version = "0.16", git = "https://github.com/chevdor/subwasm" }
wasm-loader = { version = "0.16", git = "https://github.com/chevdor/subwasm" }
