name: Release tracker
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

env:
  AUTH: ${{ secrets.GITHUB_TOKEN }}
  RUST_TOOLCHAIN: nightly
  PYTHON_VERSION: "3.10"
  RUNTIME_OVERRIDES_LINK: https://github.com/hack-ink/runtime-overrides/releases/download
  RUNTIME_OVERRIDES_VERSION: v0.9.0-rc1
jobs:
  track-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust ${{ env.RUST_TOOLCHAIN }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install runtime-overrides $${{ env.RUNTIME_OVERRIDES_VERSION }}
        run: |
          curl -L ${{ env.RUNTIME_OVERRIDES_LINK }}/${{ env.RUNTIME_OVERRIDES_VERSION }}/runtime-overrides.tar.zst | tar --zst -xv
          sudo mv runtime-overrides /usr/bin
          sudo chmod u+x /usr/bin/runtime-overrides
      - name: Fetch latest code
        uses: actions/checkout@v3
      - name: Run
        run: |
          pip install -r .github/requirements.txt
          python3 .github/release-tracker.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: AurevoirXavier
          commit_user_email: xavier@inv.cafe
          commit_author: AurevoirXavier <xavier@inv.cafe>
